# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/ui_maxp.ui'
#
# Created: Fri Jun  6 21:56:18 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_maxp_ui(object):
    def setupUi(self, maxp_ui):
        maxp_ui.setObjectName(_fromUtf8("maxp_ui"))
        maxp_ui.resize(422, 578)
        maxp_ui.setMinimumSize(QtCore.QSize(422, 578))
        maxp_ui.setMaximumSize(QtCore.QSize(422, 578))
        self.buttonBox = QtGui.QDialogButtonBox(maxp_ui)
        self.buttonBox.setGeometry(QtCore.QRect(210, 530, 166, 33))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(maxp_ui)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 381, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 331, 171))
        self.groupBox.setMinimumSize(QtCore.QSize(331, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 291, 138))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setSpacing(12)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.threshold_spin = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.threshold_spin.setProperty("value", 99.99)
        self.threshold_spin.setObjectName(_fromUtf8("threshold_spin"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.threshold_spin)
        self.attribute_combo = QtGui.QComboBox(self.formLayoutWidget_2)
        self.attribute_combo.setObjectName(_fromUtf8("attribute_combo"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.attribute_combo)
        self.layer_combo = QtGui.QComboBox(self.formLayoutWidget_2)
        self.layer_combo.setObjectName(_fromUtf8("layer_combo"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.layer_combo)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.threshold_attr_combo = QtGui.QComboBox(self.formLayoutWidget_2)
        self.threshold_attr_combo.setObjectName(_fromUtf8("threshold_attr_combo"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.threshold_attr_combo)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 270, 331, 111))
        self.groupBox_2.setMinimumSize(QtCore.QSize(331, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 291, 81))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setSpacing(12)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.tabumax_spin = QtGui.QSpinBox(self.formLayoutWidget)
        self.tabumax_spin.setMinimum(1)
        self.tabumax_spin.setProperty("value", 5)
        self.tabumax_spin.setObjectName(_fromUtf8("tabumax_spin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tabumax_spin)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.tabulength_spin = QtGui.QSpinBox(self.formLayoutWidget)
        self.tabulength_spin.setMinimum(1)
        self.tabulength_spin.setProperty("value", 5)
        self.tabulength_spin.setObjectName(_fromUtf8("tabulength_spin"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tabulength_spin)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.browse_button = QtGui.QPushButton(self.tab)
        self.browse_button.setGeometry(QtCore.QRect(280, 410, 80, 26))
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.layer_path = QtGui.QLineEdit(self.tab)
        self.layer_path.setGeometry(QtCore.QRect(20, 410, 241, 25))
        self.layer_path.setObjectName(_fromUtf8("layer_path"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 390, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.add_canvas = QtGui.QCheckBox(self.tab)
        self.add_canvas.setGeometry(QtCore.QRect(20, 440, 341, 21))
        self.add_canvas.setObjectName(_fromUtf8("add_canvas"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 200, 331, 61))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 291, 31))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setSpacing(12)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_2 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.maxit_spin = QtGui.QSpinBox(self.formLayoutWidget_3)
        self.maxit_spin.setMinimum(1)
        self.maxit_spin.setMaximum(99999)
        self.maxit_spin.setProperty("value", 2)
        self.maxit_spin.setObjectName(_fromUtf8("maxit_spin"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxit_spin)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.help_browser = QtGui.QTextBrowser(self.tab_2)
        self.help_browser.setGeometry(QtCore.QRect(10, 10, 351, 451))
        self.help_browser.setHtml(_fromUtf8("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.help_browser.setAcceptRichText(False)
        self.help_browser.setOpenExternalLinks(True)
        self.help_browser.setObjectName(_fromUtf8("help_browser"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.progressBar = QtGui.QProgressBar(maxp_ui)
        self.progressBar.setGeometry(QtCore.QRect(30, 530, 161, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))

        self.retranslateUi(maxp_ui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), maxp_ui.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), maxp_ui.reject)
        QtCore.QObject.connect(self.layer_combo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.threshold_attr_combo.update)
        QtCore.QObject.connect(self.threshold_attr_combo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.threshold_spin.update)
        QtCore.QMetaObject.connectSlotsByName(maxp_ui)

    def retranslateUi(self, maxp_ui):
        maxp_ui.setWindowTitle(_translate("maxp_ui", "Clusterpy light: Max-p", None))
        self.groupBox.setTitle(_translate("maxp_ui", "Clustering parameters", None))
        self.label_5.setText(_translate("maxp_ui", "Layer", None))
        self.label_6.setText(_translate("maxp_ui", "Clustering attribute", None))
        self.label_7.setText(_translate("maxp_ui", "Threshold value", None))
        self.label_8.setText(_translate("maxp_ui", "Threshold attribute", None))
        self.groupBox_2.setTitle(_translate("maxp_ui", "Local Search parameters", None))
        self.label_4.setText(_translate("maxp_ui", "Tabu List length", None))
        self.label_3.setText(_translate("maxp_ui", "Tabu maximum steps", None))
        self.browse_button.setText(_translate("maxp_ui", "Browse", None))
        self.label.setText(_translate("maxp_ui", "Output layer", None))
        self.add_canvas.setText(_translate("maxp_ui", "Add to map canvas", None))
        self.groupBox_3.setTitle(_translate("maxp_ui", "Construction phase parameters", None))
        self.label_2.setText(_translate("maxp_ui", "Maximum iterations", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("maxp_ui", "Algorithm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("maxp_ui", "Help", None))

